#include "Rules.h"

Rules* IsReq;
Rules.ReqUnivCredits = 14;
Rules.ReqTrackCredits = 40;
Rules.ReqMajorCredits = 78;
Rules.UnivCompulsory.push_back(ENG 151);
Rules.UnivCompulsory.push_back(ENG 152);
Rules.UnivCompulsory.push_back(SCH 260);
Rules.UnivCompulsory.push_back(SCH 261);
Rules.UnivCompulsory.push_back(SCH 262);
Rules.UnivCompulsory.push_back(SCH 263);
Rules.UnivCompulsory.push_back(SCH 264);
Rules.UnivElective.push_back(ENV 301);
Rules.UnivElective.push_back(ENV 512);
Rules.UnivElective.push_back(ENV 527);
Rules.UnivElective.push_back(HIS 302);
Rules.UnivElective.push_back(HIS 304);
Rules.UnivElective.push_back(PHIL 301);
Rules.TrackCompulsory.push_back(BIOL 101);
Rules.TrackCompulsory.push_back(BIOL 111);
Rules.TrackCompulsory.push_back(CHEM 101);
Rules.TrackCompulsory.push_back(CHEM 111);
Rules.MajorCompulsory.push_back(CIE 202);
Rules.MajorCompulsory.push_back(CIE 205);
Rules.MajorCompulsory.push_back(CIE 206);
Rules.MajorElective.push_back(402);
Rules.MajorElective.push_back(416);
Rules.MajorElective.push_back(418);
Rules.MajorElective.push_back(427);
